name: Yarn Build 
run-name: Yarn Build
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_commit_to_gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
      - name: Deploy GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        if:   ${{ github.ref == 'refs/heads/main' }}  
        with:
          folder: dist # The folder the action should deploy.      
